# Generated by Django 4.2.29 on 2026-04-22 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0002_studentprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfileModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.SlugField(max_length=64, unique=True)),
                ('module_name', models.CharField(max_length=128)),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['module_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfileRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_type', models.SlugField(max_length=64)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfileQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.SlugField(max_length=64)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_intelligence_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfileModuleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='profile_intelligence.studentprofilemoduleregistry')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_data', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfileIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_score', models.PositiveSmallIntegerField(default=0)),
                ('engagement_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('is_at_risk', models.BooleanField(db_index=True, default=False)),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfileContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_code', models.SlugField(max_length=128)),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STALE', 'Stale'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=16)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfileBehaviorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('actions_count', models.PositiveIntegerField(default=0)),
                ('average_session_duration', models.FloatField(default=0.0)),
                ('engagement_level', models.CharField(choices=[('INACTIVE', 'Inactive'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='INACTIVE', max_length=16)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_metrics', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfileActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACTION', 'Action'), ('UPDATE', 'Update'), ('VIEW', 'View'), ('SYSTEM', 'System')], db_index=True, max_length=16)),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('action_code', models.SlugField(max_length=128)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfileSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion_type', models.CharField(choices=[('PROFILE', 'Profile'), ('CV', 'CV'), ('CAREER', 'Career'), ('ENGAGEMENT', 'Engagement'), ('RISK', 'Risk')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=16)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['is_completed', '-priority', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['student_profile', 'is_completed'], name='profile_int_student_4a627c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfileStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, choices=[('NEW', 'New'), ('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('ENGAGED', 'Engaged'), ('AT_RISK', 'At risk'), ('DORMANT', 'Dormant'), ('GRADUATED', 'Graduated')], default='', max_length=16)),
                ('to_state', models.CharField(choices=[('NEW', 'New'), ('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('ENGAGED', 'Engaged'), ('AT_RISK', 'At risk'), ('DORMANT', 'Dormant'), ('GRADUATED', 'Graduated')], max_length=16)),
                ('trigger_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER_ACTION', 'User action'), ('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual')], default='SYSTEM', max_length=16)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-transitioned_at'],
                'indexes': [models.Index(fields=['student_profile', '-transitioned_at'], name='profile_int_student_d38fc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_rate', models.PositiveSmallIntegerField(default=0)),
                ('engagement_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['student_profile', '-snapshot_date'], name='profile_int_student_11b439_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentprofilesnapshot',
            constraint=models.UniqueConstraint(fields=('student_profile', 'snapshot_date'), name='uniq_snapshot_per_student_per_day'),
        ),
        migrations.AddIndex(
            model_name='studentprofilerisk',
            index=models.Index(fields=['student_profile', 'is_active'], name='profile_int_student_96d2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofilerisk',
            index=models.Index(fields=['risk_type', 'risk_level'], name='profile_int_risk_ty_b61c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofilequerylog',
            index=models.Index(fields=['executed_by', '-created_at'], name='profile_int_execute_025311_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofilemoduledata',
            index=models.Index(fields=['student_profile', '-last_updated_at'], name='profile_int_student_98f9fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofilemoduledata',
            constraint=models.UniqueConstraint(fields=('student_profile', 'module'), name='uniq_module_data_per_student'),
        ),
        migrations.AddIndex(
            model_name='studentprofileindicator',
            index=models.Index(fields=['is_at_risk', '-updated_at'], name='profile_int_is_at_r_47e4c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofilecontext',
            constraint=models.UniqueConstraint(fields=('student_profile', 'context_code'), name='uniq_context_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studentprofilebehaviormetric',
            constraint=models.UniqueConstraint(fields=('student_profile', 'source_app'), name='uniq_behavior_metric_per_student_app'),
        ),
        migrations.AddIndex(
            model_name='studentprofileactivitylog',
            index=models.Index(fields=['student_profile', '-created_at'], name='profile_int_student_2721b1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofileactivitylog',
            index=models.Index(fields=['source_app', 'action_code'], name='profile_int_source__4c0930_idx'),
        ),
    ]
