# Generated by Django 4.2.29 on 2026-04-26 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.SlugField(max_length=128)),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('entity_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.SlugField(max_length=128)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push notification')], db_index=True, max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('REALTIME', 'Realtime'), ('DAILY_DIGEST', 'Daily digest'), ('WEEKLY_DIGEST', 'Weekly digest'), ('NEVER', 'Never')], default='REALTIME', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.SlugField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('action_url', models.CharField(blank=True, default='', max_length=512)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_app_notifications', to='notifications.notificationevent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='notifications.notification')),
            ],
            options={
                'ordering': ['remind_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'remind_at'], name='notificatio_status_620135_idx'), models.Index(fields=['notification', 'status'], name='notificatio_notific_2ec290_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push notification')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed')], db_index=True, default='PENDING', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notificationevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_bd6a1d_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_ab7494_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationrecipient',
            constraint=models.UniqueConstraint(fields=('event', 'user', 'delivery_channel'), name='uniq_recipient_per_event_user_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'is_enabled'], name='notificatio_user_id_fb01c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'notification_type', 'channel'), name='uniq_preference_per_user_type_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['source_app', 'event_code'], name='notificatio_source__b6d9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__0a8795_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_code', '-triggered_at'], name='notificatio_event_c_8d28e4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'),
        ),
    ]
