# Generated by Django 4.2.29 on 2026-04-19 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvAiAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('suggestions_json', models.JSONField(blank=True, default=list)),
                ('strengths_json', models.JSONField(blank=True, default=list)),
                ('weaknesses_json', models.JSONField(blank=True, default=list)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='CvAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('profile_image', 'Profile Image'), ('attachment', 'Attachment')], max_length=32)),
                ('file', models.FileField(upload_to='cv/assets/%Y/%m/')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CvSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('header', 'Header'), ('contact', 'Contact'), ('summary', 'Profile Summary'), ('education', 'Education'), ('experience', 'Experience'), ('skills', 'Skills'), ('languages', 'Languages'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('custom', 'Custom')], max_length=32)),
                ('label', models.CharField(max_length=128)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('slot_name', models.CharField(blank=True, default='', max_length=64)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('content_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CvTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='cv/templates/')),
                ('category', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('creative', 'Creative')], default='modern', max_length=16)),
                ('layout_schema', models.JSONField(blank=True, default=dict)),
                ('style_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_default', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCv',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='My CV', max_length=160)),
                ('slug', models.SlugField(blank=True, default='', max_length=180)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('current_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='accounts_et_roles.studentprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_cvs', to='cv_builder.cvtemplate')),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CvVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot_json', models.JSONField()),
                ('change_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cv_builder.studentcv')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='cvtemplate',
            index=models.Index(fields=['is_active', 'is_default'], name='cv_builder__is_acti_b92e52_idx'),
        ),
        migrations.AddField(
            model_name='cvsection',
            name='student_cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cv_builder.studentcv'),
        ),
        migrations.AddField(
            model_name='cvasset',
            name='student_cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='cv_builder.studentcv'),
        ),
        migrations.AddField(
            model_name='cvaianalysis',
            name='student_cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cv_builder.studentcv'),
        ),
        migrations.AddIndex(
            model_name='studentcv',
            index=models.Index(fields=['student_profile', 'is_primary'], name='cv_builder__student_f7bcaa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcv',
            index=models.Index(fields=['student_profile', 'status'], name='cv_builder__student_77fa4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentcv',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student_profile',), name='uniq_primary_cv_per_student'),
        ),
        migrations.AddConstraint(
            model_name='cvversion',
            constraint=models.UniqueConstraint(fields=('student_cv', 'version_number'), name='uniq_version_number_per_cv'),
        ),
        migrations.AddIndex(
            model_name='cvsection',
            index=models.Index(fields=['student_cv', 'order_index'], name='cv_builder__student_d1ad19_idx'),
        ),
        migrations.AddIndex(
            model_name='cvasset',
            index=models.Index(fields=['student_cv', 'asset_type'], name='cv_builder__student_37f37a_idx'),
        ),
        migrations.AddIndex(
            model_name='cvaianalysis',
            index=models.Index(fields=['student_cv', '-analyzed_at'], name='cv_builder__student_90e395_idx'),
        ),
    ]
