# Generated by Django 4.2.29 on 2026-04-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0002_cvsharelink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cvsharelink',
            new_name='cv_builder__student_978c63_idx',
            old_name='cv_builder__student_share_idx',
        ),
    ]
