# Generated by Django 4.2.29 on 2026-04-26 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettingsRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SECURITY', 'Security'), ('NOTIFICATIONS', 'Notifications'), ('INTEGRATIONS', 'Integrations'), ('UI', 'UI'), ('FEATURE_FLAGS', 'Feature flags')], db_index=True, default='GENERAL', max_length=32)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=16)),
                ('default_value_json', models.JSONField(blank=True, default=dict)),
                ('is_user_configurable', models.BooleanField(db_index=True, default=False)),
                ('is_system', models.BooleanField(default=False, help_text='Built-in entries cannot be deleted by admins.')),
            ],
            options={
                'ordering': ['category', 'key'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_values', to='settings_app.appsettingsregistry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('requires_2fa_to_change', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='appsettingsregistry',
            index=models.Index(fields=['category', 'is_user_configurable'], name='settings_ap_categor_8d6830_idx'),
        ),
        migrations.AddIndex(
            model_name='userappsettings',
            index=models.Index(fields=['user', 'setting'], name='settings_ap_user_id_48352f_idx'),
        ),
        migrations.AddConstraint(
            model_name='userappsettings',
            constraint=models.UniqueConstraint(fields=('user', 'setting'), name='uniq_user_setting'),
        ),
    ]
