# Generated by Django 4.2.29 on 2026-04-26 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0002_studentprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncadrantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_workload', models.PositiveSmallIntegerField(default=0, help_text='Live count of currently assigned students.')),
                ('max_concurrent_students', models.PositiveSmallIntegerField(default=0)),
                ('availability_calendar_json', models.JSONField(blank=True, default=dict)),
                ('expertise_areas', models.JSONField(blank=True, default=list)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('supervisor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadrant_profile', to='accounts_et_roles.supervisorprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(db_index=True, help_text='Format: 2025-2026', max_length=16)),
                ('level', models.CharField(blank=True, default='', help_text='e.g. L1, L2, M1, M2, ING-1', max_length=16)),
                ('student_capacity', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='admin_management.filiere')),
            ],
            options={
                'ordering': ['-academic_year', 'filiere', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(db_index=True, max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='admin_management.classgroup')),
                ('encadrant_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='admin_management.encadrantprofile')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-academic_year', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('access_scope', models.ForeignKey(blank=True, help_text='Optional bridge to the canonical AccessScope hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_role_assignments', to='accounts_et_roles.accessscope')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='admin_management.classgroup')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='admin_management.filiere')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_assignments', to='accounts_et_roles.role')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_level', models.CharField(choices=[('SUPER', 'Super admin'), ('STANDARD', 'Standard admin'), ('READONLY', 'Read-only admin')], db_index=True, default='STANDARD', max_length=16)),
                ('last_admin_login_at', models.DateTimeField(blank=True, null=True)),
                ('audit_pin_hash', models.CharField(blank=True, default='', help_text='SHA-256 of the PIN used to confirm sensitive admin actions.', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('STUDENTS', 'Students'), ('ENCADRANTS', 'Encadrants'), ('CLASS_GROUPS', 'Class groups'), ('FILIERES', 'Filieres'), ('ASSIGNMENTS', 'Assignments'), ('ROLES', 'Roles'), ('OTHER', 'Other')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['import_type', 'status'], name='admin_manag_import__51c621_idx'), models.Index(fields=['started_by', '-created_at'], name='admin_manag_started_bf772c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['filiere', 'academic_year'], name='admin_manag_filiere_589c59_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['student_profile', 'academic_year'], name='admin_manag_student_9350dc_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_group', 'academic_year'], name='admin_manag_class_g_1e5008_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['encadrant_profile', 'is_active'], name='admin_manag_encadra_ded594_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student_profile', 'academic_year'), name='uniq_active_assignment_per_year'),
        ),
        migrations.AddIndex(
            model_name='adminroleassignment',
            index=models.Index(fields=['target_user', 'is_active'], name='admin_manag_target__25971d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminroleassignment',
            index=models.Index(fields=['role', 'is_active'], name='admin_manag_role_id_489f55_idx'),
        ),
        migrations.AddIndex(
            model_name='adminroleassignment',
            index=models.Index(fields=['filiere', 'is_active'], name='admin_manag_filiere_cac727_idx'),
        ),
        migrations.AddIndex(
            model_name='adminroleassignment',
            index=models.Index(fields=['class_group', 'is_active'], name='admin_manag_class_g_807d1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('target_user', 'role', 'filiere', 'class_group'), name='uniq_active_admin_role_per_scope'),
        ),
    ]
