# Generated by Django 4.2.29 on 2026-04-26 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.SlugField(max_length=128)),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('action_code', models.SlugField(help_text='Verb of what happened: CREATE / UPDATE / DELETE / APPROVE / ...', max_length=64)),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('entity_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=16)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, help_text='Group multiple events from the same logical operation.', null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryRetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_app', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_code', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('retention_days', models.PositiveIntegerField()),
                ('action_on_expiry', models.CharField(choices=[('DELETE', 'Delete'), ('ANONYMIZE', 'Anonymize'), ('ARCHIVE', 'Archive')], default='DELETE', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_affected_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['rule_code'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='history_his_is_acti_dac758_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoryFilterSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('is_shared', models.BooleanField(db_index=True, default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_history_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('export_type', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('XML', 'XML'), ('PDF', 'PDF'), ('GDPR_REQUEST', 'GDPR request')], db_index=True, max_length=16)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='history/exports/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryEventTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_entity_type', models.CharField(db_index=True, max_length=64)),
                ('target_entity_id', models.BigIntegerField(db_index=True)),
                ('target_role', models.CharField(choices=[('SUBJECT', 'Subject'), ('OBJECT', 'Object'), ('RELATED', 'Related'), ('BEFORE', 'Before state'), ('AFTER', 'After state')], db_index=True, default='RELATED', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='history.historyevent')),
            ],
            options={
                'ordering': ['event', 'target_role'],
            },
        ),
        migrations.CreateModel(
            name='HistoryMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('value', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('DATE', 'Date')], default='STRING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_entries', to='history.historyevent')),
            ],
            options={
                'ordering': ['event', 'key'],
                'indexes': [models.Index(fields=['key', 'value'], name='history_his_key_3ebe0f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='historymetadata',
            constraint=models.UniqueConstraint(fields=('event', 'key'), name='uniq_metadata_key_per_event'),
        ),
        migrations.AddIndex(
            model_name='historyfiltersaved',
            index=models.Index(fields=['owner', '-last_used_at'], name='history_his_owner_i_7243a2_idx'),
        ),
        migrations.AddIndex(
            model_name='historyfiltersaved',
            index=models.Index(fields=['is_shared', '-updated_at'], name='history_his_is_shar_5250b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='historyfiltersaved',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_filter_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='historyexportlog',
            index=models.Index(fields=['requested_by', '-created_at'], name='history_his_request_ecbe49_idx'),
        ),
        migrations.AddIndex(
            model_name='historyexportlog',
            index=models.Index(fields=['status', '-created_at'], name='history_his_status_ba8860_idx'),
        ),
        migrations.AddIndex(
            model_name='historyeventtarget',
            index=models.Index(fields=['target_entity_type', 'target_entity_id'], name='history_his_target__7e06ed_idx'),
        ),
        migrations.AddIndex(
            model_name='historyeventtarget',
            index=models.Index(fields=['event', 'target_role'], name='history_his_event_i_600e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='historyevent',
            index=models.Index(fields=['source_app', 'event_code'], name='history_his_source__7ebabe_idx'),
        ),
        migrations.AddIndex(
            model_name='historyevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='history_his_entity__6dd280_idx'),
        ),
        migrations.AddIndex(
            model_name='historyevent',
            index=models.Index(fields=['actor_user', '-occurred_at'], name='history_his_actor_u_480698_idx'),
        ),
        migrations.AddIndex(
            model_name='historyevent',
            index=models.Index(fields=['source_app', '-occurred_at'], name='history_his_source__3e7332_idx'),
        ),
        migrations.AddIndex(
            model_name='historyevent',
            index=models.Index(fields=['severity', '-occurred_at'], name='history_his_severit_4ce453_idx'),
        ),
        migrations.AddIndex(
            model_name='historyevent',
            index=models.Index(fields=['correlation_id', 'occurred_at'], name='history_his_correla_14177e_idx'),
        ),
    ]
