# Generated by Django 4.2.29 on 2026-04-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('LOGOUT', 'Logout'), ('LOGOUT_ALL', 'Logout all'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_RESET_COMPLETED', 'Password reset completed'), ('PASSWORD_CHANGED', 'Password changed'), ('SUSPICIOUS_LOCKOUT', 'Suspicious lockout'), ('SESSION_REVOKED', 'Session revoked'), ('TOKEN_REFRESHED', 'Token refreshed'), ('PROVIDER_LINKED', 'Provider linked')], db_index=True, max_length=48)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('success', models.BooleanField(db_index=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('', ''), ('invalid_credentials', 'Invalid credentials'), ('inactive_account', 'Inactive account'), ('locked', 'Locked'), ('unknown_user', 'Unknown user'), ('provider_error', 'Provider error')], default='', max_length=64)),
                ('provider', models.CharField(default='LOCAL', max_length=32)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['identifier', 'attempted_at'], name='authenticat_identif_74cd40_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='authenticat_ip_addr_140591_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='authenticat_user_id_cfaa9f_idx'), models.Index(fields=['user', 'expires_at'], name='authenticat_user_id_643cc4_idx')],
            },
        ),
    ]
