# Generated by Django 4.2.29 on 2026-04-26 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_builder', '0003_rename_cv_builder__student_share_idx_cv_builder__student_978c63_idx'),
        ('accounts_et_roles', '0002_studentprofile_availability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_shared', models.BooleanField(db_index=True, default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=280)),
                ('description', models.TextField(blank=True, default='')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='offers/logos/')),
                ('company_website', models.URLField(blank=True, default='', max_length=512)),
                ('company_description', models.TextField(blank=True, default='')),
                ('location_city', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('location_country', models.CharField(blank=True, default='', max_length=128)),
                ('is_remote', models.BooleanField(db_index=True, default=False)),
                ('is_hybrid', models.BooleanField(default=False)),
                ('offer_type', models.CharField(choices=[('PFE', "PFE (Projet Fin d'Études)"), ('PFA', "PFA (Projet Fin d'Année)"), ('INTERNSHIP', 'Internship'), ('ALTERNANCE', 'Alternance'), ('JOB', 'Job'), ('OTHER', 'Other')], db_index=True, default='INTERNSHIP', max_length=16)),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('compensation_currency', models.CharField(blank=True, default='MAD', max_length=8)),
                ('compensation_period', models.CharField(choices=[('NOT_SPECIFIED', 'Not specified'), ('MONTHLY', 'Monthly'), ('TOTAL', 'Total'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily')], default='NOT_SPECIFIED', max_length=16)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('required_languages', models.JSONField(blank=True, default=list)),
                ('min_education_level', models.CharField(blank=True, choices=[('BAC', 'Baccalaureate'), ('BAC_PLUS_2', 'Bac+2'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('INGENIEUR', 'Ingénieur'), ('DOCTORAT', 'Doctorat')], default='', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, default='', max_length=1024)),
                ('external_source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferTargetingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('FILIERE', 'Filière'), ('CLASS_GROUP', 'Class group'), ('LEVEL', 'Education level'), ('SKILL', 'Skill'), ('LANGUAGE', 'Language'), ('AVAILABILITY', 'Availability'), ('LOCATION', 'Location'), ('CUSTOM', 'Custom')], db_index=True, max_length=32)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('is_inclusive', models.BooleanField(default=True, help_text='True = must match (whitelist). False = must NOT match (blacklist).')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeting_rules', to='stage.internshipoffer')),
            ],
            options={
                'ordering': ['priority', 'rule_type'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview scheduled'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], db_index=True, default='SUBMITTED', max_length=16)),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('match_score_at_apply', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_status_change_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('cv_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cv_builder.cvaianalysis')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='stage.internshipoffer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cv_builder.studentcv')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_applications', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalLinkFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CLICK', 'Click'), ('REDIRECT', 'Redirect'), ('EXTERNAL_APPLY', 'External apply')], db_index=True, default='CLICK', max_length=24)),
                ('target_url', models.URLField(max_length=1024)),
                ('referrer', models.URLField(blank=True, default='', max_length=1024)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_followups', to='stage.internshipoffer')),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_link_followups', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stage.candidatecollection')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-priority', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('COVER_LETTER', 'Cover letter'), ('TRANSCRIPT', 'Transcript'), ('RECOMMENDATION', 'Recommendation letter'), ('PORTFOLIO', 'Portfolio'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], db_index=True, max_length=32)),
                ('file', models.FileField(upload_to='applications/documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stage.offerapplication')),
            ],
            options={
                'ordering': ['document_type', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentOfferMatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, help_text='0.00 - 100.00', max_digits=5)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('is_recommended', models.BooleanField(db_index=True, default=False)),
                ('computed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='stage.internshipoffer')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_match_scores', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-score', '-computed_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['student_profile', '-score'], name='stage_stude_student_15363c_idx'), models.Index(fields=['offer', '-score'], name='stage_stude_offer_i_4339e6_idx'), models.Index(fields=['is_recommended', '-score'], name='stage_stude_is_reco_835528_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentoffermatchscore',
            constraint=models.UniqueConstraint(fields=('student_profile', 'offer'), name='uniq_match_score_per_student_offer'),
        ),
        migrations.AddIndex(
            model_name='offertargetingrule',
            index=models.Index(fields=['offer', 'rule_type'], name='stage_offer_offer_i_b612f4_idx'),
        ),
        migrations.AddIndex(
            model_name='offertargetingrule',
            index=models.Index(fields=['offer', 'is_active'], name='stage_offer_offer_i_e08dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='offerapplication',
            index=models.Index(fields=['student_profile', '-applied_at'], name='stage_offer_student_692bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='offerapplication',
            index=models.Index(fields=['offer', 'status'], name='stage_offer_offer_i_14aa36_idx'),
        ),
        migrations.AddIndex(
            model_name='offerapplication',
            index=models.Index(fields=['status', '-applied_at'], name='stage_offer_status_64caed_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW', 'ACCEPTED'))), fields=('student_profile', 'offer'), name='uniq_active_application_per_student_offer'),
        ),
        migrations.AddIndex(
            model_name='internshipoffer',
            index=models.Index(fields=['status', '-published_at'], name='stage_inter_status_9e72f6_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipoffer',
            index=models.Index(fields=['offer_type', 'status'], name='stage_inter_offer_t_ca234a_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipoffer',
            index=models.Index(fields=['company_name', 'status'], name='stage_inter_company_8117ef_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipoffer',
            index=models.Index(fields=['external_source', 'external_id'], name='stage_inter_externa_464907_idx'),
        ),
        migrations.AddConstraint(
            model_name='internshipoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_source', 'external_id'), name='uniq_external_offer_per_source'),
        ),
        migrations.AddIndex(
            model_name='externallinkfollowup',
            index=models.Index(fields=['offer', '-created_at'], name='stage_exter_offer_i_331ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='externallinkfollowup',
            index=models.Index(fields=['student_profile', '-created_at'], name='stage_exter_student_098465_idx'),
        ),
        migrations.AddIndex(
            model_name='externallinkfollowup',
            index=models.Index(fields=['event_type', '-created_at'], name='stage_exter_event_t_73d2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecollectionitem',
            index=models.Index(fields=['collection', '-priority'], name='stage_candi_collect_87686c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecollectionitem',
            index=models.Index(fields=['student_profile', '-added_at'], name='stage_candi_student_e14986_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatecollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'student_profile'), name='uniq_student_per_collection'),
        ),
        migrations.AddIndex(
            model_name='candidatecollection',
            index=models.Index(fields=['owner', '-updated_at'], name='stage_candi_owner_i_3f9c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application', 'document_type'], name='stage_appli_applica_a85abf_idx'),
        ),
    ]
