# Generated by Django 4.2.29 on 2026-04-26 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0002_studentprofile_availability_and_more'),
        ('admin_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('PROGRESS', 'Progress'), ('EVALUATION', 'Evaluation'), ('INTERIM', 'Interim'), ('FINAL', 'Final'), ('INCIDENT', 'Incident')], db_index=True, default='PROGRESS', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=16)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Optional 0.00 - 100.00 evaluation score.', max_digits=5, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('encadrant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_reports', to='admin_management.encadrantprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supervision_reports', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_reports', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('workspace_type', models.CharField(choices=[('PROJECT', 'Project'), ('COHORT', 'Cohort'), ('TEAM', 'Team'), ('INDIVIDUAL', 'Individual')], db_index=True, default='PROJECT', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('owner_encadrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to='admin_management.encadrantprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], db_index=True, default='TODO', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='accounts_et_roles.studentprofile')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='encadrant.workspace')),
            ],
            options={
                'ordering': ['status', '-priority', 'due_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupervisedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary supervisor'), ('CO_SUPERVISOR', 'Co-supervisor'), ('EXTERNAL', 'External supervisor'), ('JURY', 'Jury member')], db_index=True, default='PRIMARY', max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('encadrant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_students', to='admin_management.encadrantprofile')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to='accounts_et_roles.studentprofile')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to='encadrant.workspace')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('change_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='encadrant.report')),
            ],
            options={
                'ordering': ['-version_number'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='encadrant.workspace'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('meeting_type', models.CharField(choices=[('ONE_ON_ONE', 'One-on-one'), ('GROUP', 'Group'), ('JURY', 'Jury session'), ('REVIEW', 'Review'), ('MILESTONE', 'Milestone')], db_index=True, default='ONE_ON_ONE', max_length=16)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show')], db_index=True, default='SCHEDULED', max_length=16)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_url', models.URLField(blank=True, default='', max_length=512)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('encadrant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='admin_management.encadrantprofile')),
                ('students', models.ManyToManyField(blank=True, related_name='meetings', to='accounts_et_roles.studentprofile')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='encadrant.workspace')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('MEETING', 'Meeting'), ('DEADLINE', 'Deadline'), ('REMINDER', 'Reminder'), ('OUT_OF_OFFICE', 'Out of office'), ('OTHER', 'Other')], db_index=True, default='MEETING', max_length=16)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('encadrant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_events', to='admin_management.encadrantprofile')),
                ('related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to='encadrant.meeting')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to='encadrant.task')),
            ],
            options={
                'ordering': ['start_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner_encadrant', 'status'], name='encadrant_w_owner_e_aeab12_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['workspace_type', 'status'], name='encadrant_w_workspa_ccf39f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'status'], name='encadrant_t_workspa_ba6a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to_student', 'status'], name='encadrant_t_assigne_c03f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_at'], name='encadrant_t_status_9019ec_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisedstudent',
            index=models.Index(fields=['encadrant_profile', 'is_active'], name='encadrant_s_encadra_cf57ff_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisedstudent',
            index=models.Index(fields=['student_profile', 'is_active'], name='encadrant_s_student_9e9e35_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisedstudent',
            index=models.Index(fields=['workspace', 'is_active'], name='encadrant_s_workspa_b67275_idx'),
        ),
        migrations.AddConstraint(
            model_name='supervisedstudent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'PRIMARY')), fields=('student_profile', 'workspace', 'role'), name='uniq_active_primary_supervisor_per_student_workspace'),
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.UniqueConstraint(fields=('report', 'version_number'), name='uniq_report_version_number'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['student_profile', '-created_at'], name='encadrant_r_student_c76821_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['encadrant_profile', '-created_at'], name='encadrant_r_encadra_818383_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='encadrant_r_status_8fa12e_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['encadrant_profile', '-scheduled_at'], name='encadrant_m_encadra_bc21db_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['workspace', '-scheduled_at'], name='encadrant_m_workspa_d09a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', '-scheduled_at'], name='encadrant_m_status_1b6fba_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['encadrant_profile', 'start_at'], name='encadrant_a_encadra_103e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['event_type', 'start_at'], name='encadrant_a_event_t_a7b447_idx'),
        ),
    ]
