# Generated by Django 4.2.29 on 2026-04-26 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0002_studentprofile_availability_and_more'),
        ('stage', '0001_initial'),
        ('admin_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=280)),
                ('body', models.TextField()),
                ('summary', models.CharField(blank=True, default='', max_length=512)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=16)),
                ('publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('allow_comments', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAnnouncementPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_via_email', models.BooleanField(default=True)),
                ('notify_via_in_app', models.BooleanField(default=True)),
                ('is_muted', models.BooleanField(db_index=True, default=False)),
                ('announcement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_preferences', to='announcements.announcementtype')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_preferences', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAnnouncementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('SAVE', 'Save'), ('DISMISS', 'Dismiss'), ('SHARE', 'Share')], db_index=True, max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_actions', to='announcements.announcement')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_actions', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, help_text='0.00 - 100.00', max_digits=5)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('is_recommended', models.BooleanField(db_index=True, default=False)),
                ('computed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_scores', to='announcements.announcement')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_recommendations', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-score', '-computed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncementTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('ALL', 'All users'), ('FILIERE', 'Filière'), ('CLASS_GROUP', 'Class group'), ('ROLE', 'Role'), ('USER', 'Specific user'), ('LEVEL', 'Education level'), ('CUSTOM', 'Custom')], db_index=True, max_length=32)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('is_inclusive', models.BooleanField(default=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='announcements.announcement')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_targets', to='admin_management.classgroup')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_targets', to='admin_management.filiere')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_targets', to='accounts_et_roles.role')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_announcement_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncementOfferLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_link', to='announcements.announcement')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_links', to='stage.internshipoffer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='announcements/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.announcement')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='announcements.announcementtype'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studentannouncementpreference',
            constraint=models.UniqueConstraint(fields=('student_profile', 'announcement_type'), name='uniq_preference_per_student_type'),
        ),
        migrations.AddIndex(
            model_name='studentannouncementaction',
            index=models.Index(fields=['student_profile', '-created_at'], name='announcemen_student_78a09d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentannouncementaction',
            index=models.Index(fields=['announcement', 'action_type'], name='announcemen_announc_c99c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationscore',
            index=models.Index(fields=['student_profile', '-score'], name='announcemen_student_4fb6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationscore',
            index=models.Index(fields=['announcement', '-score'], name='announcemen_announc_d831c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationscore',
            constraint=models.UniqueConstraint(fields=('student_profile', 'announcement'), name='uniq_recommendation_per_student_announcement'),
        ),
        migrations.AddIndex(
            model_name='announcementtarget',
            index=models.Index(fields=['announcement', 'target_type'], name='announcemen_announc_cbad35_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementofferlink',
            index=models.Index(fields=['offer', '-created_at'], name='announcemen_offer_i_18f902_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementofferlink',
            constraint=models.UniqueConstraint(fields=('announcement', 'offer'), name='uniq_announcement_offer_link'),
        ),
        migrations.AddIndex(
            model_name='announcementattachment',
            index=models.Index(fields=['announcement'], name='announcemen_announc_7caff7_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', '-published_at'], name='announcemen_status_63c2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['announcement_type', 'status'], name='announcemen_announc_a1b8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_pinned', '-published_at'], name='announcemen_is_pinn_c75b4f_idx'),
        ),
    ]
