# Generated by Django 4.2.29 on 2026-04-26 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0002_studentprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('resource_type', models.CharField(choices=[('ROOM', 'Room'), ('EQUIPMENT', 'Equipment'), ('VEHICLE', 'Vehicle'), ('OTHER', 'Other')], db_index=True, default='ROOM', max_length=16)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('is_bookable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('ATTESTATION', 'Attestation'), ('CONVENTION', 'Convention'), ('CERTIFICATE', 'Certificate'), ('AUTHORIZATION', 'Authorization'), ('REPORT', 'Report'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_workflow', models.BooleanField(default=True, help_text='If false, requests are auto-approved.')),
                ('default_validity_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_code', models.SlugField(max_length=64)),
                ('step_label', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('decision', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_CHANGES', 'Request changes'), ('FORWARD', 'Forward'), ('', 'None')], default='', max_length=24)),
                ('performed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='documents.documentrequest')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_request', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.SlugField(max_length=64)),
                ('rule_definition_json', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='documents.documenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(db_index=True, default='fr', max_length=8)),
                ('file_template', models.FileField(upload_to='documents/templates/')),
                ('placeholders_json', models.JSONField(blank=True, default=list)),
                ('layout_schema', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='documents.documenttype')),
            ],
            options={
                'ordering': ['document_type', 'language', '-is_default'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentRequestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.SlugField(max_length=128)),
                ('field_label', models.CharField(blank=True, default='', max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('FILE', 'File'), ('JSON', 'JSON')], default='TEXT', max_length=16)),
                ('field_value_json', models.JSONField(blank=True, default=dict)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_errors_json', models.JSONField(blank=True, default=list)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.documentrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_document_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='target_student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='accounts_et_roles.studentprofile'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='target_user',
            field=models.ForeignKey(help_text='User the document is about (often = requester, may differ for staff-on-behalf).', on_delete=django.db.models.deletion.PROTECT, related_name='target_document_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='documents.documenttemplate'),
        ),
        migrations.CreateModel(
            name='DocumentOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/outputs/%Y/%m/')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('HTML', 'HTML')], default='PDF', max_length=8)),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_metadata_json', models.JSONField(blank=True, default=dict)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='documents.documentrequest')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/attachments/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('attachment_type', models.CharField(choices=[('SUPPORTING', 'Supporting document'), ('VALIDATION', 'Validation document'), ('GENERATED', 'Generated output'), ('OTHER', 'Other')], db_index=True, default='SUPPORTING', max_length=16)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.documentrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('ROLE_REQUIRED', 'Role required'), ('MAX_DURATION', 'Max duration'), ('ADVANCE_NOTICE', 'Advance notice'), ('BLACKOUT', 'Blackout window'), ('APPROVAL_REQUIRED', 'Approval required')], db_index=True, max_length=24)),
                ('rule_definition_json', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='documents.administrativeresource')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['resource', 'is_active'], name='documents_r_resourc_5e9d63_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True, default='')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CHECKED_IN', 'Checked in'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-show')], db_index=True, default='PENDING', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_approved', to=settings.AUTH_USER_MODEL)),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations_made', to=settings.AUTH_USER_MODEL)),
                ('reserved_for_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_for_me', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='documents.administrativeresource')),
            ],
            options={
                'ordering': ['-start_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['resource', 'start_at', 'end_at'], name='documents_r_resourc_3b3320_idx'), models.Index(fields=['reserved_by', '-start_at'], name='documents_r_reserve_9679ee_idx'), models.Index(fields=['status', '-start_at'], name='documents_r_status_7c0016_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gt', models.F('start_at'))), name='reservation_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='documentworkflow',
            index=models.Index(fields=['document_request', 'status'], name='documents_d_documen_a8ef85_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttyperule',
            index=models.Index(fields=['document_type', 'is_active'], name='documents_d_documen_c835e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttyperule',
            constraint=models.UniqueConstraint(fields=('document_type', 'rule_code'), name='uniq_rule_per_document_type'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['document_type', 'language'], name='documents_d_documen_b042d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('document_type', 'language'), name='uniq_default_template_per_type_lang'),
        ),
        migrations.AddConstraint(
            model_name='documentrequestfield',
            constraint=models.UniqueConstraint(fields=('document_request', 'field_name'), name='uniq_field_per_request'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['status', '-created_at'], name='documents_d_status_d36ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['requested_by', '-created_at'], name='documents_d_request_df71d5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['target_user', '-created_at'], name='documents_d_target__f2f9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['document_type', 'status'], name='documents_d_documen_3d9e82_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoutput',
            index=models.Index(fields=['document_request', '-generated_at'], name='documents_d_documen_ed6a15_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['document_request', 'attachment_type'], name='documents_d_documen_db3e15_idx'),
        ),
    ]
