# Generated by Django 4.2.29 on 2026-04-26 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_et_roles', '0002_studentprofile_availability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('adjustments_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('breakdown_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('TUITION', 'Tuition'), ('REGISTRATION', 'Registration'), ('EXAM', 'Exam'), ('HOUSING', 'Housing'), ('TRANSPORT', 'Transport'), ('MISC', 'Miscellaneous')], db_index=True, default='TUITION', max_length=16)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('default_currency', models.CharField(default='MAD', max_length=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['category', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Positive = student owes; negative = credit balance.', max_digits=12)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=16)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('payment_date', models.DateTimeField(db_index=True)),
                ('reference_number', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='srf.financialaccount')),
            ],
            options={
                'ordering': ['-payment_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('method_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHECK', 'Check'), ('CARD', 'Card'), ('MOBILE', 'Mobile payment'), ('OTHER', 'Other')], db_index=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_reference', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['method_type', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(upload_to='srf/receipts/%Y/%m/')),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sha256_hash', models.CharField(blank=True, default='', max_length=64)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='srf.payment')),
            ],
            options={
                'ordering': ['-issued_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='srf.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('campaign_type', models.CharField(choices=[('REMINDER', 'Reminder'), ('OVERDUE', 'Overdue notice'), ('RECEIPT', 'Receipt distribution'), ('SCHOLARSHIP', 'Scholarship announcement'), ('GENERAL', 'General')], db_index=True, max_length=16)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('IN_APP', 'In-app')], default='EMAIL', max_length=16)),
                ('target_filter_json', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_srf_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_type', models.CharField(choices=[('CHARGE', 'Charge'), ('CREDIT', 'Credit'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], db_index=True, default='CHARGE', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=16)),
                ('academic_year', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative amount paid against this line.', max_digits=12)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='srf.financialaccount')),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='srf.feetype')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hold_type', models.CharField(choices=[('PAYMENT', 'Payment hold'), ('DOCUMENT', 'Document issuance hold'), ('GRADE', 'Grade release hold'), ('REGISTRATION', 'Registration hold'), ('OTHER', 'Other')], db_index=True, max_length=16)),
                ('reason', models.TextField()),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum unpaid amount that triggers this hold.', max_digits=12, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_holds', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_holds', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_holds', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-placed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExemptionAndAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('SCHOLARSHIP', 'Scholarship'), ('EXEMPTION', 'Exemption'), ('DISCOUNT', 'Discount'), ('WRITE_OFF', 'Write-off'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('justification', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='srf.financialaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account', '-payment_date'], name='srf_payment_account_4d5f17_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-payment_date'], name='srf_payment_status_4cbf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', '-payment_date'], name='srf_payment_payment_b47933_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['campaign_type', 'status'], name='srf_notific_campaig_57f097_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='srf_notific_status_113803_idx'),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['account', 'status'], name='srf_financi_account_efebef_idx'),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['status', 'due_date'], name='srf_financi_status_6858f2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['academic_year', 'status'], name='srf_financi_academi_2f61ad_idx'),
        ),
        migrations.AddIndex(
            model_name='financialhold',
            index=models.Index(fields=['student_profile', 'is_active'], name='srf_financi_student_d38a94_idx'),
        ),
        migrations.AddIndex(
            model_name='financialhold',
            index=models.Index(fields=['hold_type', 'is_active'], name='srf_financi_hold_ty_e3f429_idx'),
        ),
        migrations.AddIndex(
            model_name='exemptionandadjustment',
            index=models.Index(fields=['account', 'is_active'], name='srf_exempti_account_255620_idx'),
        ),
        migrations.AddIndex(
            model_name='exemptionandadjustment',
            index=models.Index(fields=['adjustment_type', 'is_active'], name='srf_exempti_adjustm_ca976a_idx'),
        ),
    ]
